export const mockProducts = [
    {
        id: 1,
        name: 'Kanjeevaram Royal Silk Saree',
        artisan: 'Ramesh Weavers, Tamil Nadu',
        price: 150.00,
        category: 'Sarees',
        image: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?auto=format&fit=crop&q=80&w=800',
        description: 'Authentic handwoven Kanjeevaram silk saree with pure zari border. Takes 15 days to weave by skilled artisans.',
        stock: 5,
        featured: true,
    },
    {
        id: 2,
        name: 'Ikat Cotton Men\'s Kurta',
        artisan: 'Pochampally Crafts, Telangana',
        price: 45.00,
        category: 'Kurtas',
        image: 'https://images.unsplash.com/photo-1595341595011-82d8c3066d4f?auto=format&fit=crop&q=80&w=800',
        description: 'Comfortable and breathable Ikat cotton kurta featuring traditional resist-dyeing techniques.',
        stock: 12,
        featured: false,
    },
    {
        id: 3,
        name: 'Pure Pashmina Wool Shawl',
        artisan: 'Himalayan Looms, Kashmir',
        price: 200.00,
        category: 'Shawls',
        image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&q=80&w=800',
        description: 'Ultra-soft, genuine Pashmina wool shawl woven in the valleys of Kashmir. Extremely warm and lightweight.',
        stock: 3,
        featured: true,
    },
    {
        id: 4,
        name: 'Banarasi Brocade Dupatta',
        artisan: 'Varanasi Weaves, UP',
        price: 85.00,
        category: 'Accessories',
        image: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?auto=format&fit=crop&q=80&w=800',
        description: 'Intricate golden brocade work on pure silk, perfect for festive occasions.',
        stock: 8,
        featured: false,
    },
    {
        id: 5,
        name: 'Hand-Spun Khadi Linen Shirt',
        artisan: 'Eco Threads Co., Gujarat',
        price: 55.00,
        category: 'Shirts',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800',
        description: 'Hand-spun, hand-woven Khadi linen shirt. Highly sustainable and gets softer with every wash.',
        stock: 15,
        featured: false,
    },
    {
        id: 6,
        name: 'Jamdani Fine Cotton Saree',
        artisan: 'Bengal Threads, West Bengal',
        price: 120.00,
        category: 'Sarees',
        image: 'https://images.unsplash.com/photo-1583391733959-b1d6db0b5b15?auto=format&fit=crop&q=80&w=800',
        description: 'Feather-light fine cotton saree featuring exquisite Jamdani motifs woven seamlessly into the fabric.',
        stock: 6,
        featured: true,
    },
    {
        id: 7,
        name: 'Handwoven Kilim Rug',
        artisan: 'Mirzapur Looms, UP',
        price: 250.00,
        category: 'Home Decor',
        image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
        description: 'A vibrant, flat-woven rug that adds a touch of traditional geometric art to any modern home.',
        stock: 4,
        featured: true,
    },
    {
        id: 8,
        name: 'Embroidered Cushion Covers (Set of 2)',
        artisan: 'Kutch Artisans, Gujarat',
        price: 35.00,
        category: 'Home Decor',
        image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&q=80&w=800',
        description: 'Hand-embroidered cushion covers featuring tiny mirror work and vibrant threads.',
        stock: 20,
        featured: false,
    },
    {
        id: 9,
        name: 'Kalamkari Block Print Tote',
        artisan: 'Andhra Crafts, AP',
        price: 40.00,
        category: 'Accessories',
        image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&q=80&w=800',
        description: 'A sturdy canvas tote bag showcasing traditional hand-block Kalamazoo prints using natural earthy dyes.',
        stock: 18,
        featured: false,
    },
    {
        id: 10,
        name: 'Silk Ikat Scarf',
        artisan: 'Odisha Weaves, Odisha',
        price: 65.00,
        category: 'Accessories',
        image: 'https://images.unsplash.com/photo-1614144362174-8c886e35593c?auto=format&fit=crop&q=80&w=800',
        description: 'A lightweight pure silk scarf with intricate double-ikat patterns, perfect for layering.',
        stock: 10,
        featured: true,
    }
];

export const mockOrders = [
    { id: 'ORD-8923', date: '2023-11-20', total: 150.00, status: 'Delivered', items: [{ name: 'Kanjeevaram Royal Silk Saree', qty: 1 }] },
    { id: 'ORD-8945', date: '2023-12-15', total: 45.00, status: 'Shipped', items: [{ name: 'Ikat Cotton Men\'s Kurta', qty: 1 }] }
];
